# Speed Options
dist: trusty
sudo: true

language: c

env:
  - PATH="$PATH:$HOME/.bin"

cache:
  directories:
    - $HOME/.bin
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

before_install:
  - if hash stack 2>/dev/null; then
    else
        curl -sSL https://get.haskellstack.org/ > $HOME/.stack/setup_stack.sh
        sh $HOME/.stack/setup_stack.sh -d $HOME/.bin
    fi

install:
  
  - stack setup
  - stack install hlint
  - stack install doctest

script:
  - hlint */*.hs
  - doctest */*.hs

branches:
  only:
    - master

