# Speed Options
dist: trusty
sudo: false

language: generic

env:
  - PATH="$PATH:$HOME/.bin"

cache:
  directories:
    - $HOME/.bin
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.bin '*/stack'

install:
  - stack setup
  - stack install hlint
  - stack install doctest

script:
  - hlint */*.hs
  - doctest */*.hs

branches:
  only:
    - master

